# Generated by Django 4.2.30 on 2026-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsource',
            name='attribution_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='license_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='license_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='usage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsource',
            name='type',
            field=models.CharField(choices=[('podcast', 'Podcast'), ('article', 'Article'), ('video', 'Video'), ('meme', 'Meme'), ('news', 'News'), ('image', 'Image'), ('book', 'Book')], max_length=20),
        ),
    ]
