# Generated by Django 4.2.30 on 2026-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentsource_attribution_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaditem',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Local media'), ('s3', 'Amazon S3')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='storage_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
